/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {type: "doc", id: "intro"},
    // { type: "autogenerated", dirName: "tutorial-basics" },
    // { type: "autogenerated", dirName: "tutorial-extras" },
    { type: "autogenerated", dirName: "wiki" },
    
  ],
  openApiSidebar: [
    {
      type: "category",
      label: "Product Shop",
      link: {
        type: "generated-index",
        title: "Product Shop API",
        description:
          "샵바이 Shop API 문서화 샘플 [이전 Swagger UI 참고] https://docs.shopby.co.kr/?url.primaryName=product/",
        slug: "/category/product-api"
      },
      items: require("./docs/product/shop/sidebar.ts")
    },
 {
      type: "category",
      label: "Order Shop",
      link: {
        type: "generated-index",
        title: "Order Shop API",
        description:
          "샵바이 Shop API 문서화 샘플 [이전 Swagger UI 참고] https://docs.shopby.co.kr/?url.primaryName=product/",
        slug: "/category/order-api"
      },
      items: require("./docs/order/shop/sidebar.ts")
    },
    {
      type: "category",
      label: "Admin Shop",
      link: {
        type: "generated-index",
        title: "Admin Shop API",
        description:
          "샵바이 Shop API 문서화 샘플 [이전 Swagger UI 참고] https://docs.shopby.co.kr/?url.primaryName=product/",
        slug: "/category/admin-api"
      },
      items: require("./docs/admin/shop/sidebar.ts")
    },
  ]
};

export default sidebars;