import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "order/shop/order-shop",
    },
    {
      type: "category",
      label: "Cart",
      items: [
        {
          type: "doc",
          id: "order/shop/get-cart",
          label: "장바구니 가져오기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/put-cart",
          label: "장바구니 수정하기",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/post-cart",
          label: "장바구니 등록하기",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "order/shop/delete-cart",
          label: "장바구니 삭제하기",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "order/shop/get-cart-calculate",
          label: "장바구니에서 선택된 상품금액 계산하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-cart-count",
          label: "장바구니에 담긴 상품 개수 가져오기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-cart-subset",
          label: "장바구니에서 선택된 항목만 장바구니 그룹별로 재계산하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-cart-validate",
          label: "장바구니에 저장된 모든 상품 구매 가능 여부 확인하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-cart-coupons-maximum",
          label: "장바구니 기준 최대 쿠폰 할인 금액 가져오기",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "GuestOrder",
      items: [
        {
          type: "doc",
          id: "order/shop/post-guest-cart",
          label: "비회원 장바구니 계산하기",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "order/shop/get-guest-orders-order-no",
          label: "비회원 주문 상세 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/post-guest-orders-order-no",
          label: "비회원 주문 토큰 발급하기",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "order/shop/put-guest-order-options-order-option-no-confirm",
          label: "비회원 상품 주문 구매확정 처리하기",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/put-guest-order-options-order-option-no-delivery-done",
          label: "비회원 상품 주문 배송완료 처리하기",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/put-guest-orders-order-no-cash-receipt",
          label: "현금영수증 신청정보 수정 (무통장 입금 주문)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/post-guest-orders-order-no-cash-receipt",
          label: "비회원 현금영수증 신청하기",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "order/shop/get-guest-orders-order-no-claim",
          label: "비회원 주문 상세 조회하기 (클레임 상세사유 포함)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/put-guest-orders-order-no-deliveries",
          label: "비회원 주문단위 배송정보 수정하기",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/get-guest-orders-order-no-forgot-password",
          label: "비회원 초기화된 주문 패스워드 전송하기",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "OrderConfiguration",
      items: [
        {
          type: "doc",
          id: "order/shop/get-order-configuration",
          label: "주문 설정 값 가져오기",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "OrderSheet",
      items: [
        {
          type: "doc",
          id: "order/shop/post-order-sheet",
          label: "주문서 작성하기",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "order/shop/get-order-sheet",
          label: "주문서 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/post-order-sheets-order-sheet-no-calculate",
          label: "쿠폰 및 배송지 정보가 적용된 금액 조회하기",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "order/shop/get-order-sheets-order-sheet-no-coupons",
          label: "적용할 수 있는 쿠폰 정보 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/post-order-sheets-order-sheet-no-coupons-apply",
          label: "쿠폰 적용하기",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "order/shop/post-order-sheets-order-sheet-no-coupons-calculate",
          label: "쿠폰적용금액 계산하기",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "order/shop/post-order-sheets-order-sheet-no-coupons-maximum",
          label: "최대쿠폰적용금액 계산하기",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Purchase",
      items: [
        {
          type: "doc",
          id: "order/shop/post-payments-reserve",
          label: "주문 예약하기",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "NaverPay",
      items: [
        {
          type: "doc",
          id: "order/shop/post-payments-naver-ordersheet",
          label: "네이버페이 주문서 생성하기",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "order/shop/put-payments-naver-validate",
          label: "네이버페이 상품구매 검증하기",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/post-payments-naver-wish-list",
          label: "네이버페이 찜 등록하기",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "MyOrder",
      items: [
        {
          type: "doc",
          id: "order/shop/get-profile-orders",
          label: "주문 리스트 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-profile-orders-order-no",
          label: "주문 상세 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-profile-previous-orders-summary",
          label: "마이페이지용 이전주문 수량 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-profile-order-options-summary-status",
          label: "주문 상태별 주문 옵션별 수량 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/put-profile-order-options-order-option-no-confirm",
          label: "상품 주문 구매 확정하기",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/put-profile-order-options-order-option-no-delivery-done",
          label: "상품 주문 배송완료 처리하기",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/get-profile-orders-summary-amount",
          label: "주문 상태별 주문 수량 및 금액 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-profile-orders-summary-status",
          label: "주문 상태별 주문 수량 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/put-profile-orders-order-cash-receipt",
          label: "현금영수증 신청정보 수정 (무통장 입금 주문)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/post-profile-orders-order-no-cash-receipts",
          label: "현금영수증 신청하기",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "order/shop/get-profile-orders-order-no-claim",
          label: "전체 주문취소를 위한 주문 상세 조회하기 (클레임 상세사유 포함)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/put-profile-orders-order-no-deliveries",
          label: "주문단위 배송정보 수정하기",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/get-profile-orders-order-no-payment-receipt-url",
          label: "결제 영수증 조회",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-profile-orders-order-no-simple-receipt",
          label: "간이 영수증 조회",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-profile-orders-order-no-specifications",
          label: "거래 명세서 조회 (주문 기준)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/post-profile-orders-order-no-cash-receipts-cancel",
          label: "[샵바이 스탠다드 전용] 현금영수증 취소하기",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "ShippingAddress",
      items: [
        {
          type: "doc",
          id: "order/shop/get-profile-shipping-addresses",
          label: "배송지 목록 가져오기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/post-profile-shipping-addresses",
          label: "배송지 등록하기",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "order/shop/get-profile-booked-shipping-addresses",
          label: "저장 된 배송지 목록 가져오기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-profile-shipping-address-recent",
          label: "최근 배송지 가져오기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-profile-shipping-addresses-address-no",
          label: "배송지 가져오기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/put-profile-shipping-addresses-address-no",
          label: "배송지 수정하기",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/delete-profile-shipping-addresses-address-no",
          label: "배송지 삭제하기",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "order/shop/put-profile-shipping-addresses-address-no-default",
          label: "기본 배송지 수정하기",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/get-shippings-enums",
          label: "배송 enum 정보 조회",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "RecurringPayment",
      items: [
        {
          type: "doc",
          id: "order/shop/get-recurring-payments",
          label: "정기결제 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/post-recurring-payments",
          label: "정기결제 신청하기",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "order/shop/get-recurring-payments-card",
          label: "가장 최근에 등록된 정기결제 카드 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/post-recurring-payments-card",
          label: "정기결제 카드 등록하기",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "order/shop/delete-recurring-payments-card",
          label: "회원의 모든 정기결제 카드 삭제하기",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "order/shop/get-recurring-payments-cards",
          label: "정기결제 카드 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-recurring-payments-cart",
          label: "정기결제 장바구니 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/put-recurring-payments-cart",
          label: "정기결제 장바구니 수정하기",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/post-recurring-payments-cart",
          label: "정기결제 장바구니에 추가하기",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "order/shop/delete-recurring-payments-cart",
          label: "정기결제 장바구니 삭제하기",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "order/shop/put-recurring-payments-close",
          label: "정기결제 해지하기 (bulk)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/put-recurring-payments-gifts",
          label: "정기 결제 사은품 변경",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/get-recurring-payments-next-recurring-date",
          label: "정기결제 다음배송일자 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/post-recurring-payments-order-sheets",
          label: "정기결제 주문서 작성하기",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "order/shop/put-recurring-payments-status",
          label: "정기결제 상태 변경 (bulk)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/get-recurring-payments-recurring-payment-id",
          label: "정기 결제 상세 조회",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/put-recurring-payments-card",
          label: "정기결제 카드 우선순위 변경",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/delete-recurring-payments-card-card-no",
          label: "정기결제 카드 삭제하기",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "order/shop/get-recurring-payments-cart-calculate",
          label: "정기결제 장바구니에서 선택된 상품금액 계산하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-recurring-payments-cart-subset",
          label: "정기결제 장바구니에서 선택된 항목만 장바구니 그룹별로 재계산하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/put-recurring-payments-close-recurring-payment-id",
          label: "정기결제 해지하기",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/post-recurring-payments-guest-cart",
          label: "정기결제 비회원 장바구니 계산하기",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "order/shop/get-recurring-payments-later-input-shippings",
          label: "정기결제 선물하기 나중 입력 배송지 정보 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/put-recurring-payments-later-input-shippings",
          label: "정기결제 선물하기 나중 입력 배송지 정보 수정하기",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/get-recurring-payments-order-sheets-order-sheets-no",
          label: "정기결제 주문서 가져오기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/post-recurring-payments-skip-next",
          label: "정기결제 회차 건너뛰기 (bulk)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "order/shop/get-recurring-payments-group-for-guest",
          label: "정기결제 선물하기 수령자 주문 상세 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/post-recurring-payments-group-for-guest",
          label: "정기결제 선물하기 수령자 주문 토큰 발급하기",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "order/shop/get-recurring-payments-recurring-payment-id-gifts",
          label: "정기 결제 사은품 조회",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/put-recurring-payments-delivery",
          label: "정기 결제 배송 정보 변경",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/put-recurring-payments-recurring-payment-id-status",
          label: "정기결제 상태 변경",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/put-recurring-payments-card-card-no-main",
          label: "정기결제 메인 카드 설정",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/put-recurring-payments-recurring-payment-id-skip-next",
          label: "정기결제 회차 건너뛰기",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "LaterShippingInput",
      items: [
        {
          type: "doc",
          id: "order/shop/get-later-input-areafees",
          label: "[샵바이 엔터프라이즈 전용] 지역별 추가 배송비 목록 조회하기 (배송비템플릿 번호 또는 암호화된 배송 번호 사용)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-order-encrypted-shipping-no-later-input",
          label: "[샵바이 엔터프라이즈 전용] 나중배송입력 주문 상세 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-later-input-shippings",
          label: "[샵바이 엔터프라이즈 전용] 나중 입력 배송지 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/put-later-input-shippings",
          label: "[샵바이 엔터프라이즈 전용] 나중 입력 배송지 정보 수정하기",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/get-shippings-encrypted-shipping-no-later-input",
          label: "[샵바이 엔터프라이즈 전용] 나중 입력 배송지 조회하기",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "order/shop/put-shippings-encrypted-shipping-no-later-input",
          label: "[샵바이 엔터프라이즈 전용] 나중 입력 배송지 정보 수정하기",
          className: "menu__list-item--deprecated api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "UnidentifiedDepositors",
      items: [
        {
          type: "doc",
          id: "order/shop/get-unidentified-depositors",
          label: "[샵바이프로 전용] 미확인 입급자 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-unidentified-depositors-config",
          label: "[샵바이프로 전용] 미확인 입금자 설정 조회하기",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Wish",
      items: [
        {
          type: "doc",
          id: "order/shop/get-wish",
          label: "위시리스트 리스트 가져오기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/put-wish",
          label: "위시리스트 수정하기",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "order/shop/post-wish",
          label: "위시리스트 등록하기",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "order/shop/delete-wish",
          label: "위시리스트 삭제하기",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "order/shop/get-wish-count",
          label: "위시리스트 개수 가져오기",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "MyPay",
      items: [
        {
          type: "doc",
          id: "order/shop/post-modify-main-payment",
          label: "주 결제수단 설정하기",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "order/shop/post-modify-password",
          label: "비밀번호 변경 파라미터 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-payment-infos",
          label: "등록된 결제수단 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/delete-payment-infos-pay-token",
          label: "등록된 결제수단 삭제하기",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "order/shop/get-register-payment",
          label: "결제수단 등록 webUrl를 위한 정보 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-register-user",
          label: "회원등록 webUrl를 위한 정보 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-register-user-with-payment",
          label: "회원등록후 결제수단 등록으로 바로 넘어갈 수 있도록 필요한 값 조회하기",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/delete-user",
          label: "회원서비스 해제하기",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "order/shop/delete-user-by-key",
          label: "마이페이 회원 서비스 해지하기",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "AppCard",
      items: [
        {
          type: "doc",
          id: "order/shop/get-app-card-cards",
          label: "[개발중] 앱카드 간편결제 카드사 목록 조회",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-app-card-inst-plan",
          label: "[개발중] 앱카드 할부정보 조회",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-app-card-pay-cards",
          label: "[개발중] 앱카드 간편결제카드 목록 조회",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-app-card-auth-order-no",
          label: "[개발중] 앱카드 인증결과 조회",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/delete-app-card-pay-cards-card-id",
          label: "[개발중] 앱카드 간편결제 카드 삭제",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "order/shop/get-app-card-qr-order-no",
          label: "[개발중] 앱카드 결제 QR 생성",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "PreviousOrder",
      items: [
        {
          type: "doc",
          id: "order/shop/get-previous-orders",
          label: "이전주문 검색",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-previous-order-details",
          label: "이전주문 상세조회",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-guest-previous-order-details",
          label: "비회원 이전주문 상세조회",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "order/shop/get-previous-order-guest-token",
          label: "이전주문 비회원 토큰 발급",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
